- name: Install packages
  hosts: localhost
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Uninstall unwanted apps
      ansible.builtin.dnf:
        name:
          - abrt
          - gnome-calendar
          - gnome-contacts
          - gnome-maps
          - gnome-tour
          - gnome-weather
        state: absent
        autoremove: yes
    - name: Enable the RPM Fusion repository
      dnf:
        name:
          - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
          - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
        state: present
    - name: Upgrade packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: Install the 'Development tools' package group
      ansible.builtin.dnf:
        name: "@Development tools"
        state: present
    - name: Install apps
      ansible.builtin.dnf:
        name:
          - gnome-shell-extension-appindicator
          - gnome-shell-extension-auto-move-windows
          - gnome-shell-extension-blur-my-shell
          - gnome-shell-extension-dash-to-dock
          - lutris
          - remmina
          - remmina-plugins-rdp
          - remmina-plugins-vnc
          - rhythmbox
          - siril
          - stellarium
          - syncthing
          - thunderbird
          - vlc
        state: latest
    - name: Enable Syncthing
      become: false
      ansible.builtin.systemd_service:
        name: syncthing
        enabled: true
        scope: user
        state: started
