- name: Import 1password key
  ansible.builtin.rpm_key:
    key: https://downloads.1password.com/linux/keys/1password.asc
- name: Add 1password repository
  ansible.builtin.yum_repository:
    name: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/\$basearch
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey:
      - https://downloads.1password.com/linux/keys/1password.asc
- name: Install 1password
  ansible.builtin.dnf:
    name: 1password
    state: present