- name: Add Tailscale repo
  ansible.builtin.yum_repository:
    name: tailscale
    description: Tailscale stable
    baseurl: https://pkgs.tailscale.com/stable/fedora/$basearch
    enabled: true
    repo_gpgcheck: true
    gpgcheck: true
    gpgkey: https://pkgs.tailscale.com/stable/fedora/repo.gpg
- name: Install Tailscale
  ansible.builtin.dnf:
    name: tailscale
    state: present
- name: Start Tailscale service
  ansible.builtin.systemd_service:
    name: tailscaled
    enabled: true
    state: started